lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
theme: jekyll-theme-tactile
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
exclude:
  - education
